# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.PositiveIntegerField(default=None, unique=True)),
                ('main_image', models.URLField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('brand', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('model_product', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('in_stock', models.BooleanField()),
                ('price', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('free_shipping', models.BooleanField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
